# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
City.create([
                {name: 'Abreu e Lima', state: 'PE'},
                {name: 'Afogados da Ingazeira', state: 'PE'},
                {name: 'Afranio', state: 'PE'},
                {name: 'Agrestina', state: 'PE'},
                {name: 'Agua Preta', state: 'PE'},
                {name: 'Aguas Belas', state: 'PE'},
                {name: 'Alagoinha', state: 'PE'},
                {name: 'Alianca', state: 'PE'},
                {name: 'Altinho', state: 'PE'},
                {name: 'Amaraji', state: 'PE'},
                {name: 'Angelim', state: 'PE'},
                {name: 'Aracoiaba', state: 'PE'},
                {name: 'Araripina', state: 'PE'},
                {name: 'Arcoverde', state: 'PE'},
                {name: 'Barra de Guabiraba', state: 'PE'},
                {name: 'Barreiros', state: 'PE'},
                {name: 'Belem de Maria', state: 'PE'},
                {name: 'Belem de Sao Francisco', state: 'PE'},
                {name: 'Belo Jardim', state: 'PE'},
                {name: 'Betania', state: 'PE'},
                {name: 'Bezerros', state: 'PE'},
                {name: 'Bodoco', state: 'PE'},
                {name: 'Bom Conselho', state: 'PE'},
                {name: 'Bom Jardim', state: 'PE'},
                {name: 'Bonito', state: 'PE'},
                {name: 'Brejao', state: 'PE'},
                {name: 'Brejinho', state: 'PE'},
                {name: 'Brejo da Madre de Deus', state: 'PE'},
                {name: 'Buenos Aires', state: 'PE'},
                {name: 'Buique', state: 'PE'},
                {name: 'Cabo de Santo Agostinho', state: 'PE'},
                {name: 'Cabrobo', state: 'PE'},
                {name: 'Cachoeirinha', state: 'PE'},
                {name: 'Caetes', state: 'PE'},
                {name: 'Calcado', state: 'PE'},
                {name: 'Calumbi', state: 'PE'},
                {name: 'Camaragibe', state: 'PE'},
                {name: 'Camocim de Sao Felix', state: 'PE'},
                {name: 'Camutanga', state: 'PE'},
                {name: 'Canhotinho', state: 'PE'},
                {name: 'Capoeiras', state: 'PE'},
                {name: 'Carnaiba', state: 'PE'},
                {name: 'Carnaubeira da Penha', state: 'PE'},
                {name: 'Carpina', state: 'PE'},
                {name: 'Caruaru', state: 'PE'},
                {name: 'Casinhas', state: 'PE'},
                {name: 'Catende', state: 'PE'},
                {name: 'Cedro', state: 'PE'},
                {name: 'Cha Grande', state: 'PE'},
                {name: 'Cha de Alegria', state: 'PE'},
                {name: 'Condado', state: 'PE'},
                {name: 'Correntes', state: 'PE'},
                {name: 'Cortes', state: 'PE'},
                {name: 'Cumaru', state: 'PE'},
                {name: 'Cupira', state: 'PE'},
                {name: 'Custodia', state: 'PE'},
                {name: 'Dormentes', state: 'PE'},
                {name: 'Escada', state: 'PE'},
                {name: 'Exu', state: 'PE'},
                {name: 'Feira Nova', state: 'PE'},
                {name: 'Ferreiros', state: 'PE'},
                {name: 'Flores', state: 'PE'},
                {name: 'Floresta', state: 'PE'},
                {name: 'Frei Miguelinho', state: 'PE'},
                {name: 'Gameleira', state: 'PE'},
                {name: 'Garanhuns', state: 'PE'},
                {name: 'Gloria do Goita', state: 'PE'},
                {name: 'Goiana', state: 'PE'},
                {name: 'Granito', state: 'PE'},
                {name: 'Gravata', state: 'PE'},
                {name: 'Iati', state: 'PE'},
                {name: 'Ibimirim', state: 'PE'},
                {name: 'Ibirajuba', state: 'PE'},
                {name: 'Igarassu', state: 'PE'},
                {name: 'Iguaraci', state: 'PE'},
                {name: 'Inaja', state: 'PE'},
                {name: 'Ingazeira', state: 'PE'},
                {name: 'Ipojuca', state: 'PE'},
                {name: 'Ipubi', state: 'PE'},
                {name: 'Itacuruba', state: 'PE'},
                {name: 'Itaiba', state: 'PE'},
                {name: 'Itamaraca', state: 'PE'},
                {name: 'Itambe', state: 'PE'},
                {name: 'Itapetim', state: 'PE'},
                {name: 'Itapissuma', state: 'PE'},
                {name: 'Itaquitinga', state: 'PE'},
                {name: 'Jaboatao dos Guararapes', state: 'PE'},
                {name: 'Jaqueira', state: 'PE'},
                {name: 'Jatauba', state: 'PE'},
                {name: 'Jatoba', state: 'PE'},
                {name: 'Joao Alfredo', state: 'PE'},
                {name: 'Joaquim Nabuco', state: 'PE'},
                {name: 'Jucati', state: 'PE'},
                {name: 'Jupi', state: 'PE'},
                {name: 'Jurema', state: 'PE'},
                {name: 'Lagoa Grande', state: 'PE'},
                {name: 'Lagoa do Carro', state: 'PE'},
                {name: 'Lagoa do Itaenga', state: 'PE'},
                {name: 'Lagoa do Ouro', state: 'PE'},
                {name: 'Lagoa dos Gatos', state: 'PE'},
                {name: 'Lajedo', state: 'PE'},
                {name: 'Limoeiro', state: 'PE'},
                {name: 'Macaparana', state: 'PE'},
                {name: 'Machados', state: 'PE'},
                {name: 'Manari', state: 'PE'},
                {name: 'Maraial', state: 'PE'},
                {name: 'Mirandiba', state: 'PE'},
                {name: 'Moreilandia', state: 'PE'},
                {name: 'Moreno', state: 'PE'},
                {name: 'Nazare da Mata', state: 'PE'},
                {name: 'Olinda', state: 'PE'},
                {name: 'Orobo', state: 'PE'},
                {name: 'Oroco', state: 'PE'},
                {name: 'Ouricuri', state: 'PE'},
                {name: 'Palmares', state: 'PE'},
                {name: 'Palmeirina', state: 'PE'},
                {name: 'Panelas', state: 'PE'},
                {name: 'Paranatama', state: 'PE'},
                {name: 'Parnamirim', state: 'PE'},
                {name: 'Passira', state: 'PE'},
                {name: 'Paudalho', state: 'PE'},
                {name: 'Paulista', state: 'PE'},
                {name: 'Pedra', state: 'PE'},
                {name: 'Pesqueira', state: 'PE'},
                {name: 'Petrolandia', state: 'PE'},
                {name: 'Petrolina', state: 'PE'},
                {name: 'Pocao', state: 'PE'},
                {name: 'Pombos', state: 'PE'},
                {name: 'Primavera', state: 'PE'},
                {name: 'Quipapa', state: 'PE'},
                {name: 'Quixaba', state: 'PE'},
                {name: 'Recife', state: 'PE'},
                {name: 'Riacho das Almas', state: 'PE'},
                {name: 'Ribeirao', state: 'PE'},
                {name: 'Rio Formoso', state: 'PE'},
                {name: 'Saire', state: 'PE'},
                {name: 'Salgadinho', state: 'PE'},
                {name: 'Salgueiro', state: 'PE'},
                {name: 'Saloa', state: 'PE'},
                {name: 'Sanharo', state: 'PE'},
                {name: 'Santa Cruz da Baixa Verde', state: 'PE'},
                {name: 'Santa Cruz do Capibaribe', state: 'PE'},
                {name: 'Santa Cruz', state: 'PE'},
                {name: 'Santa Filomena', state: 'PE'},
                {name: 'Santa Maria da Boa Vista', state: 'PE'},
                {name: 'Santa Maria do Cambuca', state: 'PE'},
                {name: 'Santa Terezinha', state: 'PE'},
                {name: 'Sao Benedito do Sul', state: 'PE'},
                {name: 'Sao Bento do Una', state: 'PE'},
                {name: 'Sao Caitano', state: 'PE'},
                {name: 'Sao Joao', state: 'PE'},
                {name: 'Sao Joaquim do Monte', state: 'PE'},
                {name: 'Sao Jose da Coroa Grande', state: 'PE'},
                {name: 'Sao Jose do Belmonte', state: 'PE'},
                {name: 'Sao Jose do Egito', state: 'PE'},
                {name: 'Sao Lourenco da Mata', state: 'PE'},
                {name: 'Sao Vicente Ferrer', state: 'PE'},
                {name: 'Serra Talhada', state: 'PE'},
                {name: 'Serrita', state: 'PE'},
                {name: 'Sertania', state: 'PE'},
                {name: 'Sirinhaem', state: 'PE'},
                {name: 'Solidao', state: 'PE'},
                {name: 'Surubim', state: 'PE'},
                {name: 'Tabira', state: 'PE'},
                {name: 'Tacaimbo', state: 'PE'},
                {name: 'Tacaratu', state: 'PE'},
                {name: 'Tamandare', state: 'PE'},
                {name: 'Taquaritinga do Norte', state: 'PE'},
                {name: 'Terezinha', state: 'PE'},
                {name: 'Terra Nova', state: 'PE'},
                {name: 'Timbauba', state: 'PE'},
                {name: 'Toritama', state: 'PE'},
                {name: 'Tracunhaem', state: 'PE'},
                {name: 'Trindade', state: 'PE'},
                {name: 'Triunfo', state: 'PE'},
                {name: 'Tupanatinga', state: 'PE'},
                {name: 'Tuparetama', state: 'PE'},
                {name: 'Venturosa', state: 'PE'},
                {name: 'Verdejante', state: 'PE'},
                {name: 'Vertente do Lerio', state: 'PE'},
                {name: 'Vertentes', state: 'PE'},
                {name: 'Vicencia', state: 'PE'},
                {name: 'Vitoria de Santo Antao', state: 'PE'},
                {name: 'Xexeu', state: 'PE'},

                {name: 'Campinas', state: 'SP'},
                {name: 'Rio Claro', state: 'SP'},
                {name: 'Sao Paulo', state: 'SP'}
            ])